In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("INvideos.csv", parse_dates=[1,5])
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12 15:48:08+00:00,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
2,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12 07:08:48+00:00,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
3,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13 01:14:16+00:00,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
4,il_pSa5l98w,17.14.11,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10 04:29:50+00:00,"Nenu Local|""Nenu Local Telugu Movie""|""Nani""|""S...",6106669,98612,4185,4763,https://i.ytimg.com/vi/il_pSa5l98w/default.jpg,False,False,False,Watch MCA- Middle Class Abbayi First Look Teas...

In [3]:
df.shape

(37351, 16)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37351 entries, 0 to 37350
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37351 non-null  object
 1   trending_date           37351 non-null  object
 2   title                   37351 non-null  object
 3   channel_title           37351 non-null  object
 4   category_id             37351 non-null  int64
 5   publish_time            37351 non-null  datetime64[ns, UTC]
 6   tags                    37351 non-null  object
 7   views                   37351 non-null  int64
 8   likes                   37351 non-null  int64
 9   dislikes                37351 non-null  int64
 10  comment_count           37351 non-null  int64
 11  thumbnail_link          37351 non-null  object
 12  comments_disabled       37351 non-null  bool
 13  ratings_disabled        37351 non-null  bool
 14  video_error_or_removed  37351 non-null  bool
 15  description             36790 non-null  object
dtypes: bool(3), datetime64[ns, UTC](1), int64(5), object(7)
memory usage: 3.8+ MB

In [12]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [14]:
# Clean the data
# Drop: can drop both rows and columns
# axis = 1: columns
# axis = 0: rows
# df = df.drop(['tags','thumbnail_link',  'description'], axis = 1)
df.drop(['tags','thumbnail_link',  'description'], axis = 1, inplace = True)

In [15]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,1096327,33966,798,882,False,False,False
1,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12 15:48:08+00:00,473988,2011,243,149,False,False,False
2,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12 07:08:48+00:00,1242680,70353,1624,2684,False,False,False
3,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13 01:14:16+00:00,464015,492,293,66,False,False,False
4,il_pSa5l98w,17.14.11,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10 04:29:50+00:00,6106669,98612,4185,4763,False,False,False

In [17]:
# Which video is the most viewed video in the data?
df.sort_values(by = 'views', ascending = False).head(20)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
5407,FlsCjmMhFmw,17.12.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,125432237,2912710,1545017,807558,False,False,False
5118,FlsCjmMhFmw,17.11.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,113876217,2811216,1470387,787174,False,False,False
4935,FlsCjmMhFmw,17.10.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,100911567,2656672,1353650,682890,False,False,False
4476,6ZfuNTqbHE8,17.07.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,89930713,2606663,53011,347982,False,False,False
4235,6ZfuNTqbHE8,17.06.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,87449453,2584674,52176,341571,False,False,False
4012,6ZfuNTqbHE8,17.05.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,84281319,2555411,51008,339708,False,False,False
3822,6ZfuNTqbHE8,17.04.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,80360459,2513102,49170,335920,False,False,False
4742,FlsCjmMhFmw,17.09.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,75969469,2251815,1127805,827755,False,False,False
3638,6ZfuNTqbHE8,17.03.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,74789251,2444956,46172,330710,False,False,False
3455,6ZfuNTqbHE8,17.02.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,66637636,2331352,41154,316185,False,False,False
3255,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,56367282,2157733,34077,303178,False,False,False
29297,u9Mv98Gr5pY,18.01.05,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,53822757,1250535,44796,135405,False,False,False
29083,u9Mv98Gr5pY,18.30.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,53071887,1243477,44414,134673,False,False,False
4567,FlsCjmMhFmw,17.08.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,52611730,1891811,884954,702784,False,False,False
28846,u9Mv98Gr5pY,18.29.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,51436997,1229059,43653,133144,False,False,False
28985,u9Mv98Gr5pY,18.29.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,51436997,1229060,43653,133144,False,False,False
28773,u9Mv98Gr5pY,18.28.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,49185287,1204863,42254,130891,False,False,False
28627,u9Mv98Gr5pY,18.28.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,49185287,1204863,42254,130891,False,False,False
28573,u9Mv98Gr5pY,18.27.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,45759148,1166895,40086,127694,False,False,False
28434,u9Mv98Gr5pY,18.27.04,VENOM - Official Trailer (HD),Sony Pictures Entertainment,24,2018-04-24 03:45:03+00:00,45759148,1166895,40086,127694,False,False,False

In [28]:
# Which video trended for most number of days?
# Simply count the number of times we have the video id in the data to get the most trended video?
df['video_id'].value_counts()[1:20]

rRr1qiJRsXk    16
l7E0kTvARsA    14
1J76wN0TPI4    14
C1Pn5Ln1R4M    13
yFFL1we4j_Y    13
y-PQiShdTKA    13
WDiK14qI3pQ    13
bYSRPuDEnTg    13
KhGyqT58vEY    12
EyPXz6hKa_s    12
XgVrYVBs2fc    12
u9Mv98Gr5pY    12
jSxKvP5VaTA    12
5hpkINjCf7A    12
mMCEvr3VWqQ    12
Tx0fhKJRaeU    12
aNwWdF8qq-M    12
ZnVIUr_BQSs    12
Nkh00qokVBA    11
Name: video_id, dtype: int64

In [26]:
df[df['video_id'] =='Nkh00qokVBA'].head(1)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
32324,Nkh00qokVBA,18.18.05,Oru Adaar Love Tamil Song Teaser | Priya Praka...,Muzik247,10,2018-05-17 06:56:47+00:00,689025,17603,5977,1658,False,False,False

# I wanted to find out the video that trended on the same day?
# days_took_to_trend = trending_date-publish_time
# days_took_to_trend ==0: Same day trending videos

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37351 entries, 0 to 37350
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37351 non-null  object
 1   trending_date           37351 non-null  object
 2   title                   37351 non-null  object
 3   channel_title           37351 non-null  object
 4   category_id             37351 non-null  int64
 5   publish_time            37351 non-null  datetime64[ns, UTC]
 6   views                   37351 non-null  int64
 7   likes                   37351 non-null  int64
 8   dislikes                37351 non-null  int64
 9   comment_count           37351 non-null  int64
 10  comments_disabled       37351 non-null  bool
 11  ratings_disabled        37351 non-null  bool
 12  video_error_or_removed  37351 non-null  bool
dtypes: bool(3), datetime64[ns, UTC](1), int64(5), object(4)
memory usage: 3.0+ MB

In [31]:
df.head(1)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,1096327,33966,798,882,False,False,False

https://gist.github.com/dgp/1b24bf2961521bd75d6c

In [34]:
# To convert the trending date column into date-time format, we need to explicilty define the pattern of the date

df['trending_date'] = pd.to_datetime(df['trending_date'], format = "%y.%d.%m")

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37351 entries, 0 to 37350
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37351 non-null  object
 1   trending_date           37351 non-null  datetime64[ns]
 2   title                   37351 non-null  object
 3   channel_title           37351 non-null  object
 4   category_id             37351 non-null  int64
 5   publish_time            37351 non-null  datetime64[ns, UTC]
 6   views                   37351 non-null  int64
 7   likes                   37351 non-null  int64
 8   dislikes                37351 non-null  int64
 9   comment_count           37351 non-null  int64
 10  comments_disabled       37351 non-null  bool
 11  ratings_disabled        37351 non-null  bool
 12  video_error_or_removed  37351 non-null  bool
dtypes: bool(3), datetime64[ns, UTC](1), datetime64[ns](1), int64(5), object(3)
memory usage: 3.0+ MB

In [37]:
df.head(1)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
0,kzwfHumJyYc,2017-11-14,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,1096327,33966,798,882,False,False,False

In [46]:
df['publish_time'] = pd.to_datetime(df['publish_time'].dt.date)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37351 entries, 0 to 37350
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37351 non-null  object
 1   trending_date           37351 non-null  datetime64[ns]
 2   title                   37351 non-null  object
 3   channel_title           37351 non-null  object
 4   category_id             37351 non-null  int64
 5   publish_time            37351 non-null  datetime64[ns]
 6   views                   37351 non-null  int64
 7   likes                   37351 non-null  int64
 8   dislikes                37351 non-null  int64
 9   comment_count           37351 non-null  int64
 10  comments_disabled       37351 non-null  bool
 11  ratings_disabled        37351 non-null  bool
 12  video_error_or_removed  37351 non-null  bool
dtypes: bool(3), datetime64[ns](2), int64(5), object(3)
memory usage: 3.0+ MB

In [48]:
df.head(1)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
0,kzwfHumJyYc,2017-11-14,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12,1096327,33966,798,882,False,False,False

In [51]:
df['days_took_to_trend'] = (df['trending_date'] - df['publish_time']).dt.days

In [54]:
df.head(10)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,days_took_to_trend
0,kzwfHumJyYc,2017-11-14,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12,1096327,33966,798,882,False,False,False,2
1,10L1hZ9qa58,2017-11-14,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12,473988,2011,243,149,False,False,False,2
2,N1vE8iiEg64,2017-11-14,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12,1242680,70353,1624,2684,False,False,False,2
3,kJzGH0PVQHQ,2017-11-14,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13,464015,492,293,66,False,False,False,1
4,il_pSa5l98w,2017-11-14,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10,6106669,98612,4185,4763,False,False,False,4
5,7MxiQ4v0EnE,2017-11-14,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11,5718766,127477,7134,8063,False,False,False,3
6,c64I9HNpiOY,2017-11-14,Padmavati : Ek Dil Ek Jaan Video Song | Deepik...,T-Series,10,2017-11-11,10588371,132738,8812,10847,False,False,False,3
7,KObFEYCaRx8,2017-11-14,Chiranjeevi in Naga Chaitanya - Samantha Recep...,Top Telugu Media,24,2017-11-13,118223,520,53,23,False,False,False,1
8,g8QsfJhFpjY,2017-11-14,New bike vs Old bike - the reality,Jump Cuts,24,2017-11-12,969030,59798,1545,2404,False,False,False,2
9,4du1KXBl4YU,2017-11-14,Mehjabi Reveals Hina Khan Dirty Politics | Exc...,TellyMasala,24,2017-11-12,632747,4330,2183,2869,False,False,False,2

In [56]:
df['days_took_to_trend'].value_counts()

1      14042
2      11989
3       6272
4       2867
5       1183
0        528
6        319
7         83
8         22
11         9
9          8
10         7
12         7
15         4
13         3
220        1
14         1
49         1
18         1
50         1
33         1
51         1
221        1
Name: days_took_to_trend, dtype: int64

In [57]:
df_hits = df[df['days_took_to_trend']==0]
df_hits.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,days_took_to_trend
430,bvmlbu5Vipg,2017-11-16,गुरुवार स्पेशल भजन : साईं बाबा रहमत की नज़र कर ...,Sonotek Bhakti,10,2017-11-16,66756,442,58,56,False,False,False,0
2372,_r0mH98oPlg,2017-11-26,RAMAYANAM PART- 7 | Bahubali Ramayanam | Unkno...,Vikram Aditya,24,2017-11-26,52202,2165,204,859,False,False,False,0
2902,j_Vlg4K05s8,2017-11-29,Dil De Kareeb | Garry Sandhu ( Full Video ) | ...,Fresh Media Records,10,2017-11-29,283742,28088,299,3806,False,False,False,0
3680,Khg8JCK6PMI,2017-12-03,RAMAYANAM PART - 10 | CLIMAX | Unknown Facts A...,Vikram Aditya,24,2017-12-03,60051,3107,73,1777,False,False,False,0
5332,wS7okEDsAWI,2017-12-12,"हनुमान चालीसा, Hanuman Chalisa Hari Om Sharan ...",T-Series Bhakti Sagar,10,2017-12-12,36535,370,37,49,False,False,False,0

In [61]:
# If I don't mention any parameter within drop_duplicate, it will look for complete duplicate row
# It will drop the one and keep the first
df_hits.drop_duplicates(inplace = True, keep = 'first')

C:\Users\SUMITH\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [62]:
# Within the videos that trended on the same day, which video is the most viewed video
df_hits.sort_values(by = "views", ascending = False)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,days_took_to_trend
35748,pnMQLrS5sTE,2018-06-06,Guru Randhawa: MADE IN INDIA | Bhushan Kumar |...,T-Series,10,2018-06-06,5295094,291480,15935,25834,False,False,False,0
36472,64UX1npgRkI,2018-06-10,Sanju: Kar Har Maidaan Fateh | Ranbir Kapoor |...,T-Series,10,2018-06-10,4852789,174930,4499,13464,False,False,False,0
16959,YBpdL9hSac4,2018-02-15,Incredibles 2 - Olympics Sneak Peek,Disney•Pixar,1,2018-02-15,1948452,122024,2256,13768,False,False,False,0
19356,i8J0cR-PY9c,2018-03-01,"Baaghi 2: Mundiyan Song | Tiger Shroff, Disha ...",T-Series,10,2018-03-01,1933869,62200,5898,3655,False,False,False,0
22734,rWmv4OzdHQw,2018-03-20,WWE RAW 19th March 2018 - Brock Lesnar dismant...,Wrestling Phobia,24,2018-03-20,1835070,15355,4621,2782,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15144,dmYYpStfSeE,2018-02-04,Ghadge & Suun - 3rd February 2018 - घाडगे & सून,Colors Marathi,24,2018-02-04,5441,25,8,2,False,False,False,0
17996,4fKgKl8W3ws,2018-02-20,Madhuban Murli LIVE - 20/2/2018 (Tuesday 7.00a...,Madhuban Murli Brahma Kumaris,27,2018-02-20,5437,195,9,9,False,False,False,0
18319,#NAME?,2018-02-22,Madhuban Murli LIVE - 22/2/2018 (Thursday 7.00...,Madhuban Murli Brahma Kumaris,27,2018-02-22,4641,185,15,5,False,False,False,0
20322,18OSLOq-bFA,2018-03-06,Madhuban Murli LIVE - 6/3/2018 (Tuesday 7.00am...,Madhuban Murli Brahma Kumaris,27,2018-03-06,4359,191,18,9,False,False,False,0
29316,iW5ZRboFCMU,2018-05-01,रट लो//1 मई 2018 Current Affairs PDF and Quiz...,Golden Era Education,27,2018-05-01,4287,312,12,100,False,False,False,0

In [64]:
# Which channel has most number of same day trending videos
df_hits['channel_title'].value_counts()[:20]

Adda247 :Official Channel of BankersAdda & SSCAdda    48
WiFiStudy                                             28
Mahendra Guru : Online Videos For Govt. Exams         16
Study IQ education                                    12
T-Series Bhakti Sagar                                 11
Vikram Aditya                                         10
Kori Pati Productions                                  8
Studio Saraswati Official                              8
WWE                                                    6
Wrestling Time                                         6
Zee Tamil                                              6
Zee Yuva                                               5
Kabaddi365.com                                         4
zeetvtelugu                                            4
Asianet                                                4
Speed Records                                          4
Pagal Gujju                                            4
T-Series                                               4
Madhuban Murli Brahma Kumaris                          4
Mazhavil Manorama                                      4
Name: channel_title, dtype: int64

Whenever you stream a video you get a good viewrship is a short period of time.

In [67]:
df_hits.groupby('channel_title').agg({"views":"sum"}).sort_values(by = "views", ascending = False)[:20]

                                                       views
channel_title
T-Series                                            13205923
WWE                                                  5308127
Wrestling Phobia                                     3670140
Speed Records                                        2221143
Disney•Pixar                                         1948452
Studio Saraswati Official                            1877699
Mythri Movie Makers                                  1738388
Lahari Music | T-Series                              1646824
Wrestling Time                                       1405443
Jimmy Kimmel Live                                    1401741
Google Developers                                    1375783
Zee News                                             1233669
5-Minute Crafts                                      1209452
The Daily Show with Trevor Noah                      1164229
T-Series Apna Punjab                                 1052263
Aditya Music                                         1031980
Colors TV                                            1010352
Adda247 :Official Channel of BankersAdda & SSCAdda    918727
Vijay Television                                      902548
WiFiStudy                                             893434

In [68]:
df_hits['category_id'].value_counts()

24    143
27    118
10     64
25     35
22     20
23     17
17     17
28     10
26      8
1       5
30      1
29      1
20      1
2       1
Name: category_id, dtype: int64

https://gist.github.com/dgp/1b24bf2961521bd75d6c

In [69]:
df_hits.groupby('category_id').agg({"views":"sum", "likes":"sum", "dislike":"sum"}).sort_values(by = "views", ascending = False)[:20]

                views
category_id
24           27639449
10           27215723
17            7541920
25            4978979
23            4718192
22            3324263
1             3180920
27            2993731
28            2868222
26            1468026
2              754383
30             225528
20             124440
29               9808

# Live Stream your video +Music+Entretainment+Sports: Get your video trending and also good viewership
# Live Stram your video + Eduction: Get you video on trending list but not good viewrship

## Analysis on the complete data

In [71]:
df.sort_values(by = 'views', ascending = False)

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,days_took_to_trend
5407,FlsCjmMhFmw,2017-12-12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06,125432237,2912710,1545017,807558,False,False,False,6
5118,FlsCjmMhFmw,2017-12-11,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06,113876217,2811216,1470387,787174,False,False,False,5
4935,FlsCjmMhFmw,2017-12-10,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06,100911567,2656672,1353650,682890,False,False,False,4
4476,6ZfuNTqbHE8,2017-12-07,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29,89930713,2606663,53011,347982,False,False,False,8
4235,6ZfuNTqbHE8,2017-12-06,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29,87449453,2584674,52176,341571,False,False,False,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5289,p3Wn9FuI2zo,2017-12-11,Dilip Ghosh and Firhad Hakim's political fight...,24 ghanta,24,2017-12-10,5098,37,5,10,False,False,False,1
18319,#NAME?,2018-02-22,Madhuban Murli LIVE - 22/2/2018 (Thursday 7.00...,Madhuban Murli Brahma Kumaris,27,2018-02-22,4641,185,15,5,False,False,False,0
20322,18OSLOq-bFA,2018-03-06,Madhuban Murli LIVE - 6/3/2018 (Tuesday 7.00am...,Madhuban Murli Brahma Kumaris,27,2018-03-06,4359,191,18,9,False,False,False,0
29316,iW5ZRboFCMU,2018-05-01,रट लो//1 मई 2018 Current Affairs PDF and Quiz...,Golden Era Education,27,2018-05-01,4287,312,12,100,False,False,False,0
29315,wntggWeDxjI,2018-05-01,"Baapmanus - बापमाणूस - Episode 118 - May 01, ...",Zee Yuva,24,2018-04-30,4024,15,0,0,False,False,False,1

In [73]:
df.drop_duplicates(subset = ['video_id'], keep = 'last', inplace = True)

In [77]:
# I wanted to find the video from T-Series that have the maximum views for the year 17-18

df[df['channel_title'] =='T-Series'].sort_values(by = "views", ascending = False)[["title", 'views']][:10]

                                                   title     views
9379   Yo Yo Honey Singh: DIL CHORI (Video) Simar Kau...  34631260
23311  Baaghi 2: Ek Do Teen Song | Jacqueline Fernand...  29503026
29663  Official Video: Raat Kamaal Hai | Guru Randhaw...  27893636
6911   Guru Randhawa: Lahore (Official Video) Bhushan...  24248933
21795  Baaghi 2 : O Saathi Video Song | Tiger Shroff ...  23476984
36423  Guru Randhawa: MADE IN INDIA | Bhushan Kumar |...  23345196
27728  Oh Humsafar Song | Neha Kakkar Himansh Kohli |...  21982564
37312  Sanju: Kar Har Maidaan Fateh | Ranbir Kapoor |...  19472216
13170  Chhote Chhote Peg (Video) | Yo Yo Honey Singh ...  18092075
15890  Raid | Official Trailer | Ajay Devgn | Ileana ...  17362743